<#
.SYNOPSIS
    Builds MMAMalodySelection.dll, the data-only Malody V selection bridge.

.DESCRIPTION
    Restores and builds MMAMalodySelection.csproj in Release, then prints the
    artifact path, its exact byte count and its SHA256.

    -BepInExDir and -GameInteropDir are REQUIRED. This script has no silent
    fallback: the two paths point at this machine's BepInEx install and at interop
    generated by this game, so guessing them would build against the wrong
    assemblies. Missing or wrong paths fail here, with instructions.

.PARAMETER BepInExDir
    BepInEx root of a BepInEx 6 Unity IL2CPP x64 install. Must contain
    core\BepInEx.Core.dll, core\BepInEx.Unity.IL2CPP.dll, core\0Harmony.dll and
    core\Il2CppInterop.Runtime.dll.

.PARAMETER GameInteropDir
    The interop folder this game generated. Must contain Il2Cppmscorlib.dll and
    UnityEngine.CoreModule.dll. BepInEx generates it the first time the game runs
    with the loader installed; it cannot be produced offline.

.EXAMPLE
    pwsh -File bridges/malody/bepinex/plugin/build.ps1 `
        -BepInExDir 'D:\Steam\steamapps\common\MalodyV\BepInEx' `
        -GameInteropDir 'D:\Steam\steamapps\common\MalodyV\BepInEx\interop'

.NOTES
    Exit codes: 0 = built; 2 = no dotnet SDK; 3 = required argument missing;
    4 = an argument path is invalid; 5 = the build reported warnings;
    6 = the artifact is missing; otherwise the exit code of dotnet.
#>
[CmdletBinding()]
param(
    [string]$BepInExDir,
    [string]$GameInteropDir
)

$ErrorActionPreference = 'Stop'

# Diagnostics are matched through their locale-independent "error CS1234" form; forcing
# the CLI language keeps the surrounding progress lines readable in bug reports as well.
$env:DOTNET_CLI_UI_LANGUAGE = 'en'
$env:DOTNET_NOLOGO = '1'

$scriptDir   = $PSScriptRoot
$project     = Join-Path $scriptDir 'MMAMalodySelection.csproj'
$nugetConfig = Join-Path $scriptDir 'NuGet.Config'
$artifact    = Join-Path $scriptDir 'bin\Release\net6.0\MMAMalodySelection.dll'

$coreAssemblies    = @('BepInEx.Core.dll', 'BepInEx.Unity.IL2CPP.dll', '0Harmony.dll', 'Il2CppInterop.Runtime.dll')
$interopAssemblies = @('Il2Cppmscorlib.dll', 'UnityEngine.CoreModule.dll')

function Get-DotnetPath {
    $command = Get-Command dotnet -CommandType Application -ErrorAction SilentlyContinue
    if ($command -and $command.Source) { return $command.Source }
    $candidates = @()
    if ($env:ProgramFiles) { $candidates += (Join-Path $env:ProgramFiles 'dotnet\dotnet.exe') }
    $candidates += 'C:\Program Files\dotnet\dotnet.exe'
    foreach ($candidate in $candidates) {
        if ($candidate -and (Test-Path -LiteralPath $candidate)) { return $candidate }
    }
    return $null
}

function Write-AssemblyReport {
    param([string]$Folder, [string[]]$Names, [string]$SubFolder)
    if (-not $Folder) {
        Write-Host '                     (not supplied)'
        return
    }
    foreach ($name in $Names) {
        $path = if ($SubFolder) { Join-Path $Folder (Join-Path $SubFolder $name) } else { Join-Path $Folder $name }
        Write-Host ("                     {0}  {1}" -f $path, $(if (Test-Path -LiteralPath $path) { '(present)' } else { '(MISSING)' }))
    }
}

function Write-Guidance {
    param([string]$UsedBepInExDir, [string]$UsedGameInteropDir)
    Write-Host ''
    Write-Host 'How to supply the two folders:' -ForegroundColor Yellow
    Write-Host '  -BepInExDir      BepInEx 6 Unity IL2CPP root, the folder that contains core\'
    Write-AssemblyReport -Folder $UsedBepInExDir -Names $coreAssemblies -SubFolder 'core'
    Write-Host '  -GameInteropDir  interop this game generated (default <BepInExDir>\interop)'
    Write-AssemblyReport -Folder $UsedGameInteropDir -Names $interopAssemblies
    Write-Host '  Interop is generated by BepInEx the first time this game runs with the loader'
    Write-Host '  installed; it cannot be generated offline and must be regenerated after a game'
    Write-Host '  update or on another machine.'
    Write-Host '  Example:'
    Write-Host "    pwsh -File `"$PSCommandPath`" ``"
    Write-Host "        -BepInExDir 'D:\Steam\steamapps\common\MalodyV\BepInEx' ``"
    Write-Host "        -GameInteropDir 'D:\Steam\steamapps\common\MalodyV\BepInEx\interop'"
}

Write-Host '=== MMAMalodySelection (Malody V selection bridge) ==='

if (-not $BepInExDir -or -not $GameInteropDir) {
    Write-Host ''
    Write-Host '[FAIL] Both -BepInExDir and -GameInteropDir are required.' -ForegroundColor Red
    Write-Host ("       Received: BepInExDir='{0}' GameInteropDir='{1}'" -f $BepInExDir, $GameInteropDir) -ForegroundColor Red
    Write-Host '       These paths are machine- and game-specific, so this script refuses to'
    Write-Host '       fall back to a default that may not exist.'
    Write-Guidance -UsedBepInExDir $BepInExDir -UsedGameInteropDir $GameInteropDir
    exit 3
}

# Normalise first: a relative path handed to MSBuild is resolved against the project
# directory, not against the caller's current directory.
$BepInExDir = [System.IO.Path]::GetFullPath($BepInExDir)
$GameInteropDir = [System.IO.Path]::GetFullPath($GameInteropDir)

$missing = @()
foreach ($name in $coreAssemblies) { $path = Join-Path $BepInExDir (Join-Path 'core' $name); if (-not (Test-Path -LiteralPath $path)) { $missing += $path } }
foreach ($name in $interopAssemblies) { $path = Join-Path $GameInteropDir $name; if (-not (Test-Path -LiteralPath $path)) { $missing += $path } }

Write-Host ("BepInExDir     : {0}" -f $BepInExDir)
Write-Host ("GameInteropDir : {0}" -f $GameInteropDir)

if ($missing.Count -gt 0) {
    Write-Host ''
    Write-Host '[FAIL] The supplied folders do not contain the required assemblies:' -ForegroundColor Red
    foreach ($path in $missing) { Write-Host ("       {0}" -f $path) -ForegroundColor Red }
    Write-Guidance -UsedBepInExDir $BepInExDir -UsedGameInteropDir $GameInteropDir
    exit 4
}

$dotnet = Get-DotnetPath
if (-not $dotnet) {
    Write-Host ''
    Write-Host '[FAIL] No dotnet SDK found.' -ForegroundColor Red
    Write-Host '       Tried: dotnet on PATH, then <ProgramFiles>\dotnet\dotnet.exe.'
    Write-Host '       Install the .NET SDK (net6.0 is the target framework; any newer SDK works)'
    Write-Host '       or put an existing SDK on PATH. https://dotnet.microsoft.com/download'
    exit 2
}
Write-Host ("dotnet         : {0} ({1})" -f $dotnet, ((& $dotnet --version) -join ' '))

foreach ($step in @(
    @{ Label = 'dotnet restore'; Arguments = @('restore', $project, '--configfile', $nugetConfig) },
    @{ Label = 'dotnet build -c Release'; Arguments = @('build', $project, '-c', 'Release', '--no-restore', "-p:BepInExDir=$BepInExDir", "-p:GameInteropDir=$GameInteropDir") }
)) {
    Write-Host ''
    Write-Host ("--- {0} ---" -f $step.Label) -ForegroundColor Cyan
    $captured = New-Object System.Collections.Generic.List[string]
    & $dotnet @($step.Arguments) 2>&1 | ForEach-Object {
        $line = "$_"
        $captured.Add($line)
        Write-Host ("    {0}" -f $line)
    }
    $code = $LASTEXITCODE
    $problems = @($captured | Where-Object { $_ -match '\berror\s+[A-Z]{2,}\d+' })
    if ($code -ne 0 -or $problems.Count -gt 0) {
        Write-Host ''
        Write-Host ("[FAIL] {0} failed (exit {1})." -f $step.Label, $code) -ForegroundColor Red
        foreach ($line in $problems) { Write-Host ("       {0}" -f $line) -ForegroundColor Red }
        Write-Guidance -UsedBepInExDir $BepInExDir -UsedGameInteropDir $GameInteropDir
        exit $(if ($code -ne 0) { $code } else { 5 })
    }
    if ($step.Label -like '*build*') { $buildLog = $captured }
}

$warnings = @($buildLog | Where-Object { $_ -match '\bwarning\s+[A-Z]{2,}\d+' })
if ($warnings.Count -gt 0) {
    Write-Host ''
    Write-Host ("[FAIL] The build reported {0} warning(s); this plugin is expected to build clean." -f $warnings.Count) -ForegroundColor Red
    foreach ($line in $warnings) { Write-Host ("       {0}" -f $line) -ForegroundColor Red }
    exit 5
}

if (-not (Test-Path -LiteralPath $artifact)) {
    Write-Host ''
    Write-Host ("[FAIL] Build succeeded but the artifact is missing: {0}" -f $artifact) -ForegroundColor Red
    exit 6
}

$item = Get-Item -LiteralPath $artifact
$hash = (Get-FileHash -LiteralPath $artifact -Algorithm SHA256).Hash

# Stage the copy the installer ships (bridges/install-bridge.ps1 reads
# malody\bepinex\plugin\MMAMalodySelection.dll). bin/ is gitignored, so without this
# step a fresh clone would install a stale DLL — or none at all.
$shipped = Join-Path $scriptDir 'MMAMalodySelection.dll'
Copy-Item -LiteralPath $artifact -Destination $shipped -Force
$shippedHash = (Get-FileHash -LiteralPath $shipped -Algorithm SHA256).Hash
if ($shippedHash -ne $hash) {
    Write-Host ''
    Write-Host ("[FAIL] The staged copy does not match the artifact: {0}" -f $shipped) -ForegroundColor Red
    exit 7
}

Write-Host ''
Write-Host '[OK] 0 errors / 0 warnings.' -ForegroundColor Green
Write-Host ("  artifact : {0}" -f $item.FullName)
Write-Host ("  size     : {0} bytes" -f $item.Length)
Write-Host ("  sha256   : {0}" -f $hash)
Write-Host ("  shipped  : {0} (installer reads this one)" -f $shipped)
exit 0
